# Пример файла конфигурации
#
# параметр: hello-message - содержит сообщение, которое будет выводиться
#                           при старте сервера
#

hello-message: '&6На сервере установлен плагин &4FirstPlugin&6!'